# Autogenerated wrapper script for oneDNN_jll for x86_64-w64-mingw32-cxx11
export libdnnl

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("oneDNN")
JLLWrappers.@declare_library_product(libdnnl, "libdnnl.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libdnnl,
        "bin\\libdnnl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
