# Autogenerated wrapper script for oneDNN_jll for x86_64-apple-darwin
export libdnnl

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("oneDNN")
JLLWrappers.@declare_library_product(libdnnl, "@rpath/libdnnl.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libdnnl,
        "lib/libdnnl.3.5.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
